# Bandit Problems
Jianwei Hu

**1. import libraries**

In [1]:
import numpy as np
import matplotlib.pyplot as plt

**2. Create **
Cited from Thompson sampling notebook by Andre Cianflone and refactor it to dataset generator

In [4]:
def generate_conversion_rates(number_of_slot_machines = 6,
                         minimum_rate = 0.01, 
                         maximum_rate = 0.15):
    return np.random.uniform(minimum_rate, 
                             maximum_rate, 
                             number_of_slot_machines)
    

In [5]:
print (generate_conversion_rates())

[0.09187933 0.10413712 0.108495   0.05204056 0.11387592 0.14714707]


In [ ]:
outcomes = np.zeros((number_of_turns, number_of_slot_machines)) #create a two-dimensional numpy array, and fill it with zeros
for turn_index in range(number_of_turns): #for each turn
    for slot_machine_index in range(number_of_slot_machines): #for each slot machine
        #Get a random number between 0.0 and 1.0.
        #If the random number is less than or equal to this slot machine's conversion rate, then set the outcome to "1".
        #Otherwise, the outcome will be "0" because the entire matrix was initially filled with zeros.
        if np.random.rand() <= conversion_rates[slot_machine_index]:
            outcomes[turn_index][slot_machine_index] = 1

#display the first 15 rows of data
print(outcomes[0:15, 0:6]) #this sort of indexing means "rows 0 to 14" (i.e., the first 15 rows) and "columns 0 through 5" (i.e., the first six c

In [18]:
def generate_outcomes(conversion_rates, number_of_turns = 1000):
    number_of_slot_machines = len(conversion_rates)
    outcomes = np.zeros((number_of_turns, number_of_slot_machines))
    
    for turn_index in range(number_of_turns):
        for slot_machine_index in range(number_of_slot_machines):
            if np.random.rand() <= conversion_rates[slot_machine_index]:
                outcomes[turn_index][slot_machine_index] = 1
            
    return outcomes

In [19]:
print(generate_outcomes(generate_conversion_rate())[0:15, 0:6])

[[0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
